In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import RidgeClassifier
from sklearn.metrics import accuracy_score, f1_score
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.impute import SimpleImputer

# For Sex

In [2]:
data_sex_train = pd.read_csv('data_train_filtered_for_sex.csv')
data_sex_test = pd.read_csv('data_test_filtered_for_sex.csv')

In [6]:
data_sex_train = data_sex_train.drop(columns=['APQ_P_APQ_P_INV', 'SDQ_SDQ_Emotional_Problems'])

In [7]:
data_sex_test = data_sex_test.drop(columns=['APQ_P_APQ_P_INV', 'SDQ_SDQ_Emotional_Problems'])

In [10]:
data_sex_test

,0throw_75thcolumn,0throw_81thcolumn,0throw_84thcolumn,0throw_85thcolumn,0throw_87thcolumn,0throw_98thcolumn,0throw_107thcolumn,0throw_123thcolumn,0throw_130thcolumn,0throw_140thcolumn,...,183throw_196thcolumn,183throw_197thcolumn,184throw_188thcolumn,184throw_189thcolumn,185throw_189thcolumn,186throw_193thcolumn,186throw_194thcolumn,191throw_192thcolumn,191throw_197thcolumn,198throw_199thcolumn
0,-0.217878,-0.270118,-0.052223,-0.389736,-0.276458,-0.366595,0.403418,-0.237697,-0.026075,-0.134562,...,0.475272,0.129814,0.243557,0.043074,0.544826,0.168735,0.359498,0.461634,0.240824,0.555732
1,-0.331628,-0.382778,-0.371968,-0.389798,-0.414460,-0.402240,0.173656,-0.181067,0.538982,0.077468,...,0.421274,0.176606,-0.090189,0.001837,0.392003,0.040167,0.361400,0.295906,0.608683,0.350027
2,-0.115130,-0.031587,-0.252965,-0.027016,-0.071282,0.025779,0.137001,0.050453,-0.222095,-0.081400,...,0.266278,0.293565,0.421614,0.142456,-0.000894,0.020912,0.332981,0.222978,0.213117,0.750987
3,-0.296514,0.038061,-0.267457,-0.173194,-0.391533,0.016137,0.370034,-0.070091,0.083891,0.223077,...,0.395772,0.355010,0.578442,0.052096,0.341820,-0.072671,0.130741,0.425634,0.152772,0.542296
4,0.123097,0.061406,-0.056358,0.049062,-0.005264,-0.209740,0.127493,-0.191406,0.436999,-0.035990,...,0.379623,0.346938,0.213097,0.274844,0.453043,-0.001653,0.390829,0.360940,0.183965,0.539823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,-0.334116,0.163332,0.010068,-0.121231,0.106574,-0.052361,0.420300,-0.136873,0.128464,0.050302,...,0.077424,0.166939,0.170505,0.123434,0.362767,-0.334864,0.275085,0.321957,0.266766,0.568742
300,-0.004611,0.212373,-0.432048,-0.139683,0.249240,-0.202069,0.237093,-0.127944,0.198718,-0.090783,...,0.272651,0.409148,0.200016,0.178605,0.462306,0.005765,0.164277,0.549172,0.297627,0.305596
301,-0.180543,0.061421,0.054551,-0.122544,-0.085767,-0.182751,0.464026,0.093351,0.569377,0.356164,...,0.320561,0.438422,0.631282,0.315062,0.490912,0.121906,0.230545,0.374783,0.444937,0.678973
302,0.116425,-0.033302,-0.048825,-0.119331,0.112909,-0.156099,0.253528,-0.339124,-0.040263,0.023793,...,0.111999,0.153213,0.311077,0.222755,0.193286,0.209129,0.387764,-0.036866,0.191030,0.530238
303,-0.004891,-0.174652,-0.035483,-0.123667,-0.125243,0.091039,0.379636,-0.121291,0.036629,0.099361,...,0.389282,-0.019398,0.603048,-0.043894,0.036033,0.293844,0.324310,0.070985,-0.022402,0.522007

# Split data

In [9]:
data_sex_train

,0throw_75thcolumn,0throw_81thcolumn,0throw_84thcolumn,0throw_85thcolumn,0throw_87thcolumn,0throw_98thcolumn,0throw_107thcolumn,0throw_123thcolumn,0throw_130thcolumn,0throw_140thcolumn,...,183throw_197thcolumn,184throw_188thcolumn,184throw_189thcolumn,185throw_189thcolumn,186throw_193thcolumn,186throw_194thcolumn,191throw_192thcolumn,191throw_197thcolumn,198throw_199thcolumn,Sex_F
0,-0.009929,-0.254163,-0.031975,-0.294171,-0.131602,-0.265231,0.371101,-0.083923,0.432327,0.281802,...,0.256575,0.748828,0.728053,0.671751,0.109487,0.141703,0.476083,0.199746,0.539032,0
1,-0.096252,0.027395,0.231600,0.088705,-0.024983,-0.059117,0.178867,-0.228113,-0.028006,-0.141415,...,0.300262,0.481281,0.345310,0.311198,-0.012180,0.282449,0.190667,0.014672,0.595978,0
2,-0.039806,-0.099795,-0.299640,-0.330875,-0.266471,-0.079532,0.601433,-0.369726,0.101826,0.431493,...,0.206865,0.561369,0.392205,0.505722,-0.016831,0.195264,0.430597,0.143500,0.605182,1
3,-0.159122,-0.047391,-0.307295,-0.376466,-0.131894,-0.385988,0.259297,-0.201115,0.290933,-0.171337,...,0.197077,0.274941,0.082132,0.577502,0.377797,0.373001,0.356579,0.708057,0.446613,1
4,-0.055320,-0.439044,-0.102250,-0.063931,-0.333399,-0.071143,0.161676,-0.240789,0.207238,0.126361,...,0.504986,0.042484,0.394607,0.463789,0.319778,0.065205,0.352243,0.264959,0.378278,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,-0.169533,-0.152733,-0.011472,-0.237914,-0.104486,-0.182753,0.151941,0.113794,0.085169,-0.194188,...,0.380492,0.741626,0.443414,0.516863,0.347972,0.381655,0.076856,0.194357,0.354333,1
1209,-0.095537,0.042406,0.113994,0.048320,-0.099102,0.222460,0.352508,0.184353,0.106294,0.318689,...,0.346297,0.639640,0.000325,0.353282,-0.098121,0.124606,0.598826,0.132968,0.537121,0
1210,-0.128866,0.166933,-0.201225,-0.381624,-0.288472,-0.330459,-0.073485,-0.112307,0.326218,-0.125160,...,0.072964,0.064576,0.103732,0.310171,-0.151364,0.176397,0.333533,0.164401,0.182633,1
1211,-0.563467,-0.268663,-0.338336,-0.109673,-0.344036,0.022717,0.444448,-0.072529,0.061317,0.049562,...,0.380915,0.377245,0.331160,0.547285,0.088911,0.235844,0.087839,0.320571,0.706737,0
1212,-0.177942,-0.408119,-0.342742,-0.348945,-0.471559,-0.421265,0.233983,-0.254703,0.142148,0.228364,...,0.316306,0.342073,0.061583,0.192388,-0.181563,0.235159,0.261813,0.386874,0.301253,1

In [56]:
X = data_sex_train.drop(columns = ['Sex_F'])
y = data_sex_train['Sex_F']

In [57]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [58]:
submission_val = pd.read_csv('Submission_val.csv')
submission_val['Sex_F'] = y_val.reset_index()['Sex_F']
submission_val.to_csv('Submission_val.csv', index=False)

In [68]:
y_val

1023    0
978     0
589     0
629     1
856     0
       ..
341     0
1041    0
466     0
1032    0
1066    0
Name: Sex_F, Length: 243, dtype: int64

In [59]:
from sklearn.decomposition import PCA

pca = PCA(n_components=100)
X_train = pca.fit_transform(X_train)
X_val = pca.transform(X_val)
X_test = pca.transform(data_sex_test)

# Models

In [13]:
class ModelEvaluator:
    def __init__(self, models : list, models_name : list[str], X_train_adhd=None, y_train_adhd=None, X_val_adhd=None, y_val_adhd=None, X_train_sex=None, y_train_sex=None, X_val_sex=None, y_val_sex=None):
        self.models = models
        self.models_name = models_name

        self.X_train_adhd = X_train_adhd
        self.y_train_adhd = y_train_adhd
        self.X_val_adhd = X_val_adhd
        self.y_val_adhd = y_val_adhd

        self.X_train_sex = X_train_sex
        self.y_train_sex = y_train_sex
        self.X_val_sex = X_val_sex
        self.y_val_sex = y_val_sex

    def evaluate(self):
        acc_adhd_collect = []
        f1_adhd_collect = []
        acc_sex_collect = []
        f1_sex_collect = []

        # MultiIndex for columns
        columns = pd.MultiIndex.from_tuples([
            ('ADHD_Outcome', 'Accuracy'),
            ('ADHD_Outcome', 'F1 Score'),
            ('Sex F', 'Accuracy'),
            ('Sex F', 'F1 Score')])
        
        df = pd.DataFrame(columns=columns, index=self.models_name)

        for index, model in enumerate(self.models):
            # Evaluate ADHD_Outcome
            model.fit(self.X_train_adhd, self.y_train_adhd)
            y_pred_adhd = model.predict(self.X_val_adhd)

            acc_adhd = accuracy_score(self.y_val_adhd, y_pred_adhd)
            f1_adhd = f1_score(self.y_val_adhd, y_pred_adhd)
            
            # Evaluate Sex_F
            model.fit(self.X_train_sex, self.y_train_sex)
            y_pred_sex = model.predict(self.X_val_sex)

            acc_sex = accuracy_score(self.y_val_sex, y_pred_sex)
            f1_sex = f1_score(self.y_val_sex, y_pred_sex)

            acc_adhd_collect.append(acc_adhd)
            f1_adhd_collect.append(f1_adhd)

            acc_sex_collect.append(acc_sex)
            f1_sex_collect.append(f1_sex)
        
        # Add results to DataFrame
        df['ADHD_Outcome', 'Accuracy'] = acc_adhd_collect
        df['ADHD_Outcome', 'F1 Score'] = f1_adhd_collect
        df['Sex F', 'Accuracy'] = acc_sex_collect
        df['Sex F', 'F1 Score'] = f1_sex_collect

        return df

In [14]:
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, GradientBoostingClassifier, VotingClassifier, HistGradientBoostingClassifier
from sklearn.ensemble import StackingClassifier, AdaBoostClassifier, BaggingClassifier
from sklearn.linear_model import SGDClassifier, Perceptron
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier



ridge = RidgeClassifier(random_state=42, alpha = 0.4)
gaussian = GaussianNB()
decision_tree = DecisionTreeClassifier(random_state=42)
logistic_regression = LogisticRegression(random_state=42, max_iter=1000, C = 0.1)
random_forest = RandomForestClassifier(random_state=42)
extra_trees = ExtraTreesClassifier(random_state=42)
gradient_boosting = GradientBoostingClassifier(random_state=42)
hist_gradient_boosting = HistGradientBoostingClassifier(random_state=42)
sgd = SGDClassifier(random_state=42)
perceptron = Perceptron(random_state=42)
svc = SVC(random_state=42)
linear_svc = LinearSVC(random_state=42)
knn = KNeighborsClassifier()
adaboost = AdaBoostClassifier(random_state=42)
bagging = BaggingClassifier(random_state=42)

stacking = StackingClassifier(estimators=[
    ('ridge', ridge),
    ('gaussian', gaussian),
    ('decision_tree', decision_tree),
    ('logistic_regression', logistic_regression),
    ('random_forest', random_forest),
    ('extra_trees', extra_trees),
    ('gradient_boosting', gradient_boosting),
    ('hist_gradient_boosting', hist_gradient_boosting),
    ('sgd', sgd),
    ('perceptron', perceptron),
    ('svc', svc),
    ('linear_svc', linear_svc),
    ('knn', knn)
], final_estimator=RidgeClassifier(random_state=42))

voting = VotingClassifier(estimators=[
    ('ridge', ridge),
    ('gaussian', gaussian),
    ('decision_tree', decision_tree),
    ('logistic_regression', logistic_regression),
    ('random_forest', random_forest),
    ('extra_trees', extra_trees),
    ('gradient_boosting', gradient_boosting),
    ('hist_gradient_boosting', hist_gradient_boosting),
    ('sgd', sgd),
    ('perceptron', perceptron),
    ('svc', svc),
    ('linear_svc', linear_svc),
    ('knn', knn)
], voting='hard')

In [15]:
list_of_models = [ridge, gaussian, decision_tree, 
                  logistic_regression, random_forest, extra_trees, 
                  gradient_boosting, hist_gradient_boosting, sgd, 
                  perceptron, svc, linear_svc, 
                  knn, stacking, voting,
                  adaboost, bagging]
list_of_models_name = ['RidgeClassifier', 'GaussianNB', 'DecisionTreeClassifier', 
                       'LogisticRegression', 'RandomForestClassifier', 'ExtraTreesClassifier',
                       'GradientBoostingClassifier', 'HistGradientBoostingClassifier', 'SGDClassifier',
                        'Perceptron', 'SVC', 'LinearSVC', 
                        'KNeighborsClassifier', 'StackingClassifier', 'VotingClassifier',
                        'AdaBoostClassifier', 'BaggingClassifier']

In [16]:
evaluator = ModelEvaluator(list_of_models, list_of_models_name, X_train_adhd=X_train, y_train_adhd=y_train, X_val_adhd=X_val, y_val_adhd = y_val, X_train_sex = X_train,
                           y_train_sex = y_train, X_val_sex = X_val, y_val_sex = y_val)
df = evaluator.evaluate()
df.sort_values(by=('ADHD_Outcome', 'F1 Score'), ascending=False)

                               ADHD_Outcome               Sex F
                                   Accuracy  F1 Score  Accuracy  F1 Score
StackingClassifier                 0.802469  0.671233  0.802469  0.671233
LogisticRegression                 0.802469  0.652174  0.802469  0.652174
GaussianNB                         0.732510  0.632768  0.732510  0.632768
LinearSVC                          0.753086  0.615385  0.753086  0.615385
SGDClassifier                      0.757202  0.614379  0.757202  0.614379
SVC                                0.790123  0.610687  0.790123  0.610687
Perceptron                         0.736626  0.594937  0.736626  0.594937
VotingClassifier                   0.781893  0.576000  0.781893  0.576000
RidgeClassifier                    0.687243  0.530864  0.687243  0.530864
KNeighborsClassifier               0.695473  0.506667  0.695473  0.506667
HistGradientBoostingClassifier     0.744856  0.474576  0.744856  0.474576
GradientBoostingClassifier         0.740741  0.470588  0.740741  0.470588
DecisionTreeClassifier             0.646091  0.455696  0.646091  0.455696
AdaBoostClassifier                 0.683128  0.437956  0.683128  0.437956
BaggingClassifier                  0.720165  0.423729  0.720165  0.423729
ExtraTreesClassifier               0.720165  0.333333  0.720165  0.333333
RandomForestClassifier             0.687243  0.254902  0.687243  0.254902

# SVC

In [61]:
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV


# Define the model
svc = SVC()

# Define the parameter grid
param_grid = {
    'C': [10, 100],
    'gamma': ['scale', 'auto', 0.001, 0.01, 0.1, 1]  # used with 'rbf' and 'poly'
}

scoring = {
    'accuracy': 'accuracy',
    'f1': 'f1',
    'recall': 'recall',
    'precision': 'precision'
}

# Grid Search
grid = GridSearchCV(svc, param_grid, cv=5, scoring=scoring, refit = 'f1')
grid.fit(X_train, y_train)

# Results
print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Best Parameters: {'C': 100, 'gamma': 'auto'}
Best Score: 0.6581216723751562

/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/envs/my_env/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [69]:
# Predict on validation/test set
y_pred = grid.best_estimator_.predict(X_val)
f1 = f1_score(y_val, y_pred)
print("Validation F1 Score:", f1)

Validation F1 Score: 0.6442953020134228

In [70]:
submission_simulation = pd.read_csv('Submission_pred.csv')
submission_simulation['Sex_F'] = y_pred
submission_simulation.to_csv('Submission_pred.csv', index=False)

In [72]:
# For test
y_test_pred = grid.best_estimator_.predict(X_test)
submission = pd.read_csv('./ThuyDuc_New/submission-ThuyDuc.csv')
submission['Sex_F'] = y_test_pred
submission.to_csv('./ThuyDuc_New/submission-ThuyDuc.csv', index=False)

In [71]:
def make_results(model_name, model_object):
    '''
    Accepts as arguments a model name (your choice - string) and
    a fit GridSearchCV model object.
  
    Returns a pandas df with the F1, recall, precision, and accuracy scores
    for the model with the best mean F1 score across all validation folds.  
    '''

    # Get all the results from the CV and put them in a df
    cv_results = pd.DataFrame(model_object.cv_results_)

    # Isolate the row of the df with the max(mean f1 score)
    best_estimator_results = cv_results.iloc[cv_results['mean_test_f1'].idxmax(), :]

    # Extract accuracy, precision, recall, and f1 score from that row
    f1 = best_estimator_results.mean_test_f1
    recall = best_estimator_results.mean_test_recall
    precision = best_estimator_results.mean_test_precision
    accuracy = best_estimator_results.mean_test_accuracy
  
    # Create table of results
    table = pd.DataFrame({'Model': [model_name],
                        'F1': [f1],
                        'Recall': [recall],
                        'Precision': [precision],
                        'Accuracy': [accuracy]
                         }
                        )
  
    return table

# Call the function on our model
result_table = make_results("Tuned Decision Tree", grid) #clf is model after using GridSearchCV

result_table

                 Model        F1    Recall  Precision  Accuracy
0  Tuned Decision Tree  0.658122  0.648575   0.670124  0.768041

# Logistic

In [78]:
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV


# Define the model
logistic = LogisticRegression(max_iter=1000, random_state=42)

# Define the parameter grid
param_grid = {
    'C': [1],  # inverse of regularization strength
    'penalty': ['l1'],  # type of regularization 'elasticnet', 'none'
    'solver': ['liblinear'],  # solvers that support L1 and elasticnet
    # 'l1_ratio': [0, 0.5, 1]  # only used if penalty='elasticnet'
}

scoring = {
    'accuracy': 'accuracy',
    'f1': 'f1',
    'recall': 'recall',
    'precision': 'precision'
}

# Grid Search
grid = GridSearchCV(logistic, param_grid, cv=5, scoring=scoring, refit = 'f1')
grid.fit(X_train, y_train)

# Results
print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Best Parameters: {'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}
Best Score: 0.6357901232163592

# Ridge

In [82]:
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV


# Define the model
ridge = RidgeClassifier(random_state=42)

# Define the parameter grid
param_grid = {
    'alpha': [4.5, 5, 5.5],  # regularization strength
}

scoring = {
    'accuracy': 'accuracy',
    'f1': 'f1',
    'recall': 'recall',
    'precision': 'precision'
}

# Grid Search
grid = GridSearchCV(ridge, param_grid, cv=5, scoring=scoring, refit = 'f1')
grid.fit(X_train, y_train)

# Results
print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Best Parameters: {'alpha': 5}
Best Score: 0.6455937762667607

# GaussianNB

In [84]:
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV


# Define the model
gnb = GaussianNB()

# Define the parameter grid
param_grid = {
    'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]  # regularization strength
}

scoring = {
    'accuracy': 'accuracy',
    'f1': 'f1',
    'recall': 'recall',
    'precision': 'precision'
}

# Grid Search
grid = GridSearchCV(gnb, param_grid, cv=5, scoring=scoring, refit = 'f1')
grid.fit(X_train, y_train)

# Results
print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Best Parameters: {'var_smoothing': 1e-09}
Best Score: 0.5522188664818317

# Stacking Classifier

In [88]:
svc = SVC(C=100, gamma='auto', random_state=42)
logistis =LogisticRegression(random_state=42, max_iter=1000, C = 1, penalty = 'l1', solver = 'liblinear')
ridge = RidgeClassifier(random_state=42, alpha = 5)
gaussian = GaussianNB()
stacking = StackingClassifier(estimators=[
    ('ridge', ridge),
    ('logistic_regression', logistic_regression),
    ('svc', svc)
], final_estimator=LogisticRegression(random_state=42, C = 5))
stacking.fit(X_train, y_train)
y_pred = stacking.predict(X_val)
f1 = f1_score(y_val, y_pred)
print("Validation F1 Score:", f1)

Validation F1 Score: 0.6376811594202898

In [89]:
submission_simulation = pd.read_csv('Submission_pred.csv')
submission_simulation['Sex_F'] = y_pred
submission_simulation.to_csv('Submission_pred.csv', index=False)

In [90]:
# For test
y_test_pred = stacking.predict(X_test)
submission = pd.read_csv('./ThuyDuc_New/submission-ThuyDuc.csv')
submission['Sex_F'] = y_test_pred
submission.to_csv('./ThuyDuc_New/submission-ThuyDuc.csv', index=False)

# Random forest

In [20]:
# This lets us see all of the columns, preventing Juptyer from redacting them.
pd.set_option('display.max_columns', None)

from sklearn.model_selection import GridSearchCV, train_test_split, RandomizedSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay

from sklearn.ensemble import RandomForestClassifier

# This module lets us save our models once we fit them.
import pickle


# Model
rf = RandomForestClassifier(random_state=42)

cv_params = {'max_depth': [2,3,4,5], 
             # 'min_samples_leaf': [1,2,3],
             'min_samples_split': [0.2, 0.4, 0.6],
             'max_features': ["sqrt",'log2',200],
             'n_estimators': [300, 500, 700, 900]
             }  

scoring = {
    'accuracy': 'accuracy',
    'f1': 'f1',
}

rf_cv = RandomizedSearchCV(rf, cv_params, scoring=scoring, cv=5, refit='f1', n_iter=10)

rf_cv.fit(X_train, y_train)

rf_cv.best_params_

rf_cv.best_score_ # based on refit parameter from GridSearchCV

0.33501358290831973

In [21]:
rf_cv.best_params_

{'n_estimators': 900,
 'min_samples_split': 0.2,
 'max_features': 200,
 'max_depth': 4}